# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\static_settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(317, 201)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scroll_area = QtWidgets.QScrollArea(Dialog)
        self.scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll_area.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scroll_area_layout_widget = QtWidgets.QWidget()
        self.scroll_area_layout_widget.setGeometry(QtCore.QRect(0, 0, 272, 130))
        self.scroll_area_layout_widget.setObjectName("scroll_area_layout_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scroll_area_layout_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.parameters_widget = QtWidgets.QWidget(self.scroll_area_layout_widget)
        self.parameters_widget.setObjectName("parameters_widget")
        self.verticalLayout_2.addWidget(self.parameters_widget)
        self.scroll_area.setWidget(self.scroll_area_layout_widget)
        self.verticalLayout.addWidget(self.scroll_area)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.buttons_layout = QtWidgets.QHBoxLayout()
        self.buttons_layout.setObjectName("buttons_layout")
        self.push_button_default = QtWidgets.QPushButton(Dialog)
        self.push_button_default.setObjectName("push_button_default")
        self.buttons_layout.addWidget(self.push_button_default)
        self.push_button_calculate = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.push_button_calculate.setFont(font)
        self.push_button_calculate.setObjectName("push_button_calculate")
        self.buttons_layout.addWidget(self.push_button_calculate)
        self.push_button_close = QtWidgets.QPushButton(Dialog)
        self.push_button_close.setObjectName("push_button_close")
        self.buttons_layout.addWidget(self.push_button_close)
        self.verticalLayout.addLayout(self.buttons_layout)

        self.retranslateUi(Dialog)
        self.push_button_close.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "STATIC parameters"))
        self.push_button_default.setText(_translate("Dialog", "Default"))
        self.push_button_calculate.setText(_translate("Dialog", "Calculate"))
        self.push_button_close.setText(_translate("Dialog", "Close"))
