# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\isolines_settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 350)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scroll_area = QtWidgets.QScrollArea(Dialog)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scroll_area_contents = QtWidgets.QWidget()
        self.scroll_area_contents.setGeometry(QtCore.QRect(0, 0, 376, 254))
        self.scroll_area_contents.setObjectName("scroll_area_contents")
        self.scroll_area_layout = QtWidgets.QVBoxLayout(self.scroll_area_contents)
        self.scroll_area_layout.setObjectName("scroll_area_layout")
        self.scroll_area.setWidget(self.scroll_area_contents)
        self.verticalLayout_2.addWidget(self.scroll_area)
        self.horizontal_layout = QtWidgets.QHBoxLayout()
        self.horizontal_layout.setObjectName("horizontal_layout")
        self.push_button_add = QtWidgets.QPushButton(Dialog)
        self.push_button_add.setObjectName("push_button_add")
        self.horizontal_layout.addWidget(self.push_button_add)
        self.push_button_delete = QtWidgets.QPushButton(Dialog)
        self.push_button_delete.setObjectName("push_button_delete")
        self.horizontal_layout.addWidget(self.push_button_delete)
        self.verticalLayout_2.addLayout(self.horizontal_layout)
        self.button_box = QtWidgets.QDialogButtonBox(Dialog)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout_2.addWidget(self.button_box, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Dialog)
        self.button_box.accepted.connect(Dialog.accept) # type: ignore
        self.button_box.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Isoline levels"))
        self.push_button_add.setText(_translate("Dialog", "Add level"))
        self.push_button_delete.setText(_translate("Dialog", "Delete level"))
